[build]
  command = "pip install -r requirements.txt && python railway_simple_start.py"
  functions = "api"

[build.environment]
  PYTHON_VERSION = "3.11.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
